### ISSUE TITLE
KeyboardLayoutGuide does not update during UIScrollView.KeyboardDismissMode.interactive animation

### ISSUE THREAD

**Issue by moyerr** [s4cha/KeyboardLayoutGuide#17]
On iOS 12, the interactive keyboard dismissal in a scroll view does not fire the `keyboardWillChangeFrameNotification` until the pan gesture ends, so any views constrained to `keyboardLayoutGuide.topAnchor` remain static throughout the interactive part of the animation.

I am not sure if this worked properly prior to iOS 12.

**Comment by shawnthroop** [comment]
@moyerr I also ran into this problem in previous iOS versions. Unfortunately, it’s a limitation in Apple’s API, not a bug.

(I’ve noticed this behavior since at least iOS 9)
