### ISSUE TITLE
Provide option to use safe area or not 

### ISSUE THREAD

**Issue by moyerr** [s4cha/KeyboardLayoutGuide#23]
Currently, if the device is running iOS 11 or newer, the `keyboardLayoutGuide.bottomAnchor` is always equal to the view's `safeAreaLayoutGuide.bottomAnchor`.

Sometimes it is nice to be able to pin views to the bottom of the screen, instead of the bottom of the safe area. It would be nice if there was a setting or parameter for determining whether or not the keyboardLayoutGuide uses the safe area.

**Comment by s4cha** [comment]
@moyerr This is a very good idea!
the api would look like so:
```swift
// Opt out of safe area if needed.
view.keyboardLayoutGuide.usesSafeArea = false
```
I created https://github.com/freshOS/KeyboardLayoutGuide/pull/27 for it, let me know if that would fit your use case !

**Comment by moyerr** [comment]
@s4cha looks great! This does fit my use case perfectly!
