### ISSUE TITLE
Weird animation when the first responder is a secured textfield.

### ISSUE THREAD

**Issue by EfraimB** [s4cha/KeyboardLayoutGuide#32]
Hello,

First of all congrats for the lightweight and great implementation. It's the best i've seen so far.
There is a bug where when switching the first responder from a normal textfield to a secured textfield, a weird animation is performed. This is cause because for some reason the keyboardWillChangeFrame notification is called not once but three times, the first one being a weird value. In order to fix this, we just have to perform the change animated only when the duration specified in the notification is greater than 0.

Here is a screen recording of the bug: https://my.pcloud.com/publink/show?code=XZO6ibkZ92g9nOy76gbtm7VTohGNg0GDcq27

**Comment by EfraimB** [comment]
Please merge my fix for this issue from this pull request https://github.com/freshOS/KeyboardLayoutGuide/pull/31 
Thank you

**Comment by s4cha** [comment]
This just got merged, a new release will follow. Thanks a ton for the fix !
