### ISSUE TITLE
Keyboard dismiss mode is interactive

### ISSUE THREAD

**Issue by atlant04** [s4cha/KeyboardLayoutGuide#35]
Layout guides are not updated if dismiss mode is interactive, is there a way to fix this?

**Comment by HarrisonXi** [comment]
Keyboard notification does not work when the keyboard changing position. Need hack something to fix the guide for interactive dismiss mode.

For example: Add a inputAccessoryView and observer its position.

**Comment by s4cha** [comment]
@atlant04 Looks more like an Apple issue than a library issue. 
Just checked and `keyboardWillChangeFrameNotification` is only called after we let go of the scroll.
One possible solution would be to use an inputAccessoryView as suggest by @HarrisonXi and in the answer :
https://stackoverflow.com/questions/48338709/cant-get-keyboard-height-when-using-interactive-keyboard-dismissal

If you ever find a solution, please reopen this issue, closing this for now.
