### ISSUE TITLE
Bringing back Cocoapods/Carthage support

### ISSUE THREAD

**Issue by SebastianOsinski** [s4cha/KeyboardLayoutGuide#36]
Hi,
firstly, thanks for great library! 
I have one question - is it possible to bring back support for other dependency managers? SPM is great and all, but it is not yet suitable for all use cases (e.g. libraries with mixed Swift/Obj-C or with resources). Because of that, lots of projects can't switch to it yet and potentially having two dependency managers (e.g. Cocoapods + SPM) might do more harm than good (e.g. resolving some subdependencies) and confuse other developers.

If that's not something you want to do, then I think it would be good idea to remove Carthage and Cocoapods badges from README

**Comment by shpuntov** [comment]
Hi there, we also have to use **Cocoapods** in our projects, and would want to add `KeyboardLayoutGuide` dependency, but the idea of dealing with two different dependency managers doesn't sound good. Please consider adding Cocoapods `podspec` file back. Thanks!

**Comment by s4cha** [comment]
Hi @SebastianOsinski,

I just removed Cocoapods & Carthage badges as you suggested. They were already marked as deprecated in the readme.
I totally understand the will to keep the other integrations but for a "one file" library, this is really cumbersome to maintain.
@shpuntov People that don't want or can't use SPM will have to use the manual installation (copy the file manually), which is a small tradeoff.

Let me know if we can close this issue.

**Comment by isaac-weisberg** [comment]
Why was it deprecated again?..

**Comment by s4cha** [comment]
@isaac-weisberg the time used to support legacy package managers is not worth it considering this is a one file library.
Closing this, feel free to reopen if needed.
