### ISSUE TITLE
Incorrect name of pod

### ISSUE THREAD

**Issue by rpanichkin** [s4cha/KeyboardLayoutGuide#4]
There's no pod specification for pod 'Keyboard+LayoutGuide'.

**Comment by s4cha** [comment]
Hello @rpanichkin 

This works on my side
```
target 'MyAppName' do
  pod 'Keyboard+LayoutGuide'
  use_frameworks!
end
```
The pod is visible here : https://cocoapods.org/pods/Keyboard+LayoutGuide
Careful another one is named `KeyboardLayoutGuide` but its not the same :)

Maybe you need to update your master repo, the pod being recent :)

**Comment by rpanichkin** [comment]
Ahhh my bad :slightly_smiling_face:

Thanks for the great tool!
